let number1 = 4;
let number2 = 6;
let product = number1 * number2;
console.log(product);
console.log(typeof product);
let charge = 8;
let payment = 5;
let amountRemaining = charge - payment;
console.log(amountRemaining);
console.log(typeof amountRemaining);
let tests = 88;
let assignments = 77;
let final = 44;
let grade = (tests + assignments + final) / 3;
console.log(grade);
console.log(typeof grade);
let firstName = "Adam";
let lastName = "Zdravkovic";
let fullName = firstName + " " + lastName;
console.log(fullName);
console.log(typeof fullName);
let pH = 2;
let isAcidic = pH < 7;
console.log(isAcidic);
console.log(typeof isAcidic);
let numberOfSoldiers = 77;
let isSparta = numberOfSoldiers === 300;
console.log(isSparta);
console.log(typeof isSparta);
let nickname = fullName;
nickname += " is the GOAT";
console.log(nickname);
console.log(typeof nickname);
